version: '3.8'

services:
  uppcl-monitor:
    build: .
    ports:
      - "3000:3000"
    volumes:
      # Persist database and backup data
      - ./data:/usr/src/app/data
      - ./backups:/usr/src/app/backups
      - ./power_data.db:/usr/src/app/power_data.db
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s